In [18]:
import pandas as pd
import io
import requests
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

In [19]:
# Loading the Data
df_train = pd.read_csv("Train.csv",na_values=['NA','?'])

#randomly shuffle rows
df_train = df_train.sample(frac=1)
df_train.head()
#df_train.Cabin.unique()


PassengerId  Survived  Pclass                            Name     Sex  \
517          518         0       3               Ryan, Mr. Patrick    male   
169          170         0       3                   Ling, Mr. Lee    male   
380          381         1       1           Bidois, Miss. Rosalie  female   
104          105         0       3  Gustafsson, Mr. Anders Vilhelm    male   
143          144         0       3             Burke, Mr. Jeremiah    male   

      Age  SibSp  Parch    Ticket      Fare Cabin Embarked  
517   NaN      0      0    371110   24.1500   NaN        Q  
169  28.0      0      0      1601   56.4958   NaN        S  
380  42.0      0      0  PC 17757  227.5250   NaN        C  
104  37.0      2      0   3101276    7.9250   NaN        S  
143  19.0      0      0    365222    6.7500   NaN        Q

In [20]:
#Handles missing vales
df_train['Age'] = df_train['Age'].fillna(df_train['Age'].median())

In [21]:
# Create dummy variables for categorical columsn
df_sex = pd.get_dummies(df_train['Sex'])
df_embarked = pd.get_dummies(df_train['Embarked'])
#df_cabin = pd.get_dummies(data_fram['Cabin'])

# Add to data fram
#Concat new columns to original dataframe 
df_train = pd.concat([df_train, df_sex,df_embarked], axis=1) #, df_cabin
df_train.head() 

PassengerId  Survived  Pclass                            Name     Sex  \
517          518         0       3               Ryan, Mr. Patrick    male   
169          170         0       3                   Ling, Mr. Lee    male   
380          381         1       1           Bidois, Miss. Rosalie  female   
104          105         0       3  Gustafsson, Mr. Anders Vilhelm    male   
143          144         0       3             Burke, Mr. Jeremiah    male   

      Age  SibSp  Parch    Ticket      Fare Cabin Embarked  female  male  C  \
517  28.0      0      0    371110   24.1500   NaN        Q       0     1  0   
169  28.0      0      0      1601   56.4958   NaN        S       0     1  0   
380  42.0      0      0  PC 17757  227.5250   NaN        C       1     0  1   
104  37.0      2      0   3101276    7.9250   NaN        S       0     1  0   
143  19.0      0      0    365222    6.7500   NaN        Q       0     1  0   

     Q  S  
517  1  0  
169  0  1  
380  0  0  
104  0  1  
143  1  0

In [22]:
x = df_train[['Pclass','Age','Parch','SibSp','female','male','C','Q','S']].values
x[:5]

array([[ 3., 28.,  0.,  0.,  0.,  1.,  0.,  1.,  0.],
       [ 3., 28.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 1., 42.,  0.,  0.,  1.,  0.,  1.,  0.,  0.],
       [ 3., 37.,  0.,  2.,  0.,  1.,  0.,  0.,  1.],
       [ 3., 19.,  0.,  0.,  0.,  1.,  0.,  1.,  0.]])

In [23]:
y = df_train[['Survived']].values
y[:5]

array([[0],
       [0],
       [1],
       [0],
       [0]], dtype=int64)

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=97)
x_train[:5]

array([[ 3., 45.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 3., 20.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 2., 52.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 3., 33.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 1., 23.,  0.,  1.,  1.,  0.,  1.,  0.,  0.]])

In [25]:
### Build neural network

model = Sequential()
#Hidden Layer 1
model.add(Dense(20, activation='relu')) # nutorns and activation function
#Hidden Layer 2
model.add(Dense(20, activation='relu'))
# Output
model.add(Dense(1))
#model.compile(loss='binary_crossentropy', optimizer='adam')
model.compile(loss='mean_squared_error', optimizer='adam')


In [26]:
## Fitting the model
## with early stopping

#model.fit(x,y,verbose=2,epochs=100)
monitor = EarlyStopping(monitor='val_loss', min_delta=0.001, patience=4, verbose=1, mode='min',restore_best_weights=True)
model.fit(x,y,validation_data=(x_test,y_test),callbacks=[monitor],verbose=2,epochs=200)
# stop the model fitting from the point from where the error no longer improves.


Train on 891 samples, validate on 179 samples
Epoch 1/200
891/891 - 0s - loss: 0.9002 - val_loss: 0.3934
Epoch 2/200
891/891 - 0s - loss: 0.2649 - val_loss: 0.2544
Epoch 3/200
891/891 - 0s - loss: 0.2195 - val_loss: 0.2332
Epoch 4/200
891/891 - 0s - loss: 0.2018 - val_loss: 0.2254
Epoch 5/200
891/891 - 0s - loss: 0.1947 - val_loss: 0.2128
Epoch 6/200
891/891 - 0s - loss: 0.1835 - val_loss: 0.2039
Epoch 7/200
891/891 - 0s - loss: 0.1800 - val_loss: 0.1941
Epoch 8/200
891/891 - 0s - loss: 0.1737 - val_loss: 0.1911
Epoch 9/200
891/891 - 0s - loss: 0.1661 - val_loss: 0.1892
Epoch 10/200
891/891 - 0s - loss: 0.1610 - val_loss: 0.1760
Epoch 11/200
891/891 - 0s - loss: 0.1556 - val_loss: 0.1959
Epoch 12/200
891/891 - 0s - loss: 0.1530 - val_loss: 0.1689
Epoch 13/200
891/891 - 0s - loss: 0.1500 - val_loss: 0.1811
Epoch 14/200
891/891 - 0s - loss: 0.1520 - val_loss: 0.1673
Epoch 15/200
891/891 - 0s - loss: 0.1442 - val_loss: 0.1624
Epoch 16/200
891/891 - 0s - loss: 0.1428 - val_loss: 0.1649
Epo

In [27]:
pred = model.predict(x)
# turn off scientific notation
np.set_printoptions(suppress=True)
pred[:5]

array([[ 0.0993401 ],
       [ 0.09629621],
       [ 0.9110073 ],
       [-0.01937328],
       [ 0.25600424]], dtype=float32)

In [28]:
## Checking Acurrcy

from sklearn.metrics import accuracy_score
# # whatis the percentage of predictions were correct? 
predict_classes = np.argmax(pred,axis=1)
actual_classes = np.argmax(y,axis=1)
accuracy = accuracy_score(actual_classes,predict_classes)
print(f"Accuracy: {accuracy}")

Accuracy: 1.0


# Now Predicting on Testing Set

In [29]:
# Loadin the data
df_test =pd.read_csv("Test.csv",na_values=['NA','?'])
df_test.head()
#df_test.Cabin.unique()


PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [30]:
#Handles missing vales
df_test['Age'] = df_test['Age'].fillna(df_test['Age'].median())

# Create dummy variables for categorical columsn
df_sex = pd.get_dummies(df_test['Sex'])
df_embarked = pd.get_dummies(df_test['Embarked'])
#df_cabin = pd.get_dummies(data_fram['Cabin'])

# Add to data fram
#Concat new columns to original dataframe 
df_test = pd.concat([df_test, df_sex,df_embarked], axis=1) #, df_cabin
df_test.head() 



PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  female  male  C  Q  S  
0  34.5      0      0   330911   7.8292   NaN        Q       0     1  0  1  0  
1  47.0      1      0   363272   7.0000   NaN        S       1     0  0  0  1  
2  62.0      0      0   240276   9.6875   NaN        Q       0     1  0  1  0  
3  27.0      0      0   315154   8.6625   NaN        S       0     1  0  0  1  
4  22.0      1      1  3101298  12.2875   NaN        S       1     0  0  0  1

In [31]:
x = df_test[['Pclass','Age','Parch','SibSp','female','male','C','Q','S']].values
x[:5]

array([[ 3. , 34.5,  0. ,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [ 3. , 47. ,  0. ,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [ 2. , 62. ,  0. ,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [ 3. , 27. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  1. ],
       [ 3. , 22. ,  1. ,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ]])

In [32]:
pred = model.predict(x)
# turn off scientific notation
np.set_printoptions(suppress=True)
pred[:5]

array([[-0.01380644],
       [ 0.55537474],
       [ 0.03507485],
       [ 0.10407962],
       [ 0.55549777]], dtype=float32)

In [33]:
i = 0
for i in range(df_test.shape[0]):
    if (pred[i] >= 0.5):
        print(str(df_test['PassengerId'][i]) + "  Estimated:" + str(pred[i]) + "-> Survived    : 1")
    else:
        print(str(df_test['PassengerId'][i]) + "  Estimated:" + str(pred[i]) + "-> Not Survived: 0")


892  Estimated:[-0.01380644]-> Not Survived: 0
893  Estimated:[0.55537474]-> Survived    : 1
894  Estimated:[0.03507485]-> Not Survived: 0
895  Estimated:[0.10407962]-> Not Survived: 0
896  Estimated:[0.55549777]-> Survived    : 1
897  Estimated:[0.20525791]-> Not Survived: 0
898  Estimated:[0.60815585]-> Survived    : 1
899  Estimated:[0.09939732]-> Not Survived: 0
900  Estimated:[0.75614035]-> Survived    : 1
901  Estimated:[0.12704004]-> Not Survived: 0
902  Estimated:[0.10407962]-> Not Survived: 0
903  Estimated:[0.23954071]-> Not Survived: 0
904  Estimated:[0.8433269]-> Survived    : 1
905  Estimated:[0.10357679]-> Not Survived: 0
906  Estimated:[0.86598074]-> Survived    : 1
907  Estimated:[0.76918566]-> Survived    : 1
908  Estimated:[0.06818523]-> Not Survived: 0
909  Estimated:[0.22912373]-> Not Survived: 0
910  Estimated:[0.5364958]-> Survived    : 1
911  Estimated:[0.61972487]-> Survived    : 1
912  Estimated:[0.30956617]-> Not Survived: 0
913  Estimated:[0.22730638]-> Not S